### ISSUE TITLE
US#1 - Homepage with list of children

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#1]
## Value Proposition

**As a** user
**I want to** see a list of the children
**so that** I can store events for each child.

## Description

![US1](https://github.com/uwoch/capstone-project/assets/127953786/f6da33f8-0a4b-472a-a948-41a7d639bc5c)

## Acceptance Criteria

- [x] a headline shows "Alle Meilensteine deines Kindes in einer App!"
- [x] a paragraph shows "Für welches Kind möchtest du loggen?"
- [x] A list of kids is displayed
- [x] the name and the picture of each child is displayed
      ​
## Tasks

- [x] create a new branch
- [x] create a headline and paragraph for the page
- [x] create a children database at mongoDB with the information of each child
- [x] create pictures of children using Playground AI
- [x] connect the database and write a function to display the kids name and the picture on the site

**Comment by DenisKorkmaz** [comment]
LGTM! The User Story is well-defined and clear.
