### ISSUE TITLE
US#4 - Delete information

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#10]
## Value Proposition

**As a** user
**I want to** be able to delete events I stored for a child
**so that** my app is always up to date.
​

## Description

![US4(1)](https://github.com/uwoch/capstone-project/assets/127953786/d8fecc0f-a13f-46ad-aae2-7f9346f04cbd)

## Acceptance Criteria

- [ ] when beeing on the edit form, a button in form of a cross is shown on each entry
- [ ] clicking the crosses deletes the entry
- [ ] a button "Speichern" is shown with which the user can save the changes (US#3)
- [ ] a button "Abbrechen" is shown so the user has the option to cancel without saving the changes (US#3)
- [ ] the update is reflected on the details page
      ​
## Tasks

- [ ] create a new branch feature/delete-information
- [ ] implement delete functions to the EditForm component
- [ ] update the details page after saving to reflect the changes
