### ISSUE TITLE
US#6 - App styling and responsiveness

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#14]
## Value Proposition

**As a** user 
**I want to** have a pretty and responsive site
**so that** I enjoy using it.
​

## Description

I don´t have a wireframe for this because I´m not sure what the final design will be.
​

## Acceptance Criteria

- [x] the app has a overall final appearance
- [x] every component has the used elements in an own stylesheet
- [x] responsive units are used when possible
- [x] the images adapt to the screen size

## Tasks

- [x] create a new branch `feature/styling`
- [x] check all used units if they are responsive
- [x] check all elements if they are used
- [x] make layout changes
- [x] use media queries for the images

**Comment by KilianBau** [comment]
Hey, you should do the research when you write your US, because the tasks should be like an instruction for your coding. So please write a bit more detailed tasks.

**Comment by uwoch** [comment]
Thanks! I did the research now and added more detailed tasks. ;-)
