### ISSUE TITLE
US#9 - Edit and Delete Child

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#15]
## Value Proposition

**As a** user
**I want to** change or delete a kid
**so that** my app is always up to date.
​

## Description

![Image](https://github.com/uwoch/capstone-project/assets/127953786/4e20da58-1edd-49b9-8dc7-a35f02b79db4)

## Acceptance Criteria

- [x] one EDIT and one DELETE button are shown next to every child
- [x] clicking the EDIT button leads to an edit form on which the user can edit the infos of a child
- [x] a button "Speichern" is shown with which the user can save the changes
- [x] a button "Abbrechen" is shown so the user has the option to cancel without saving the changes
- [x] clicking the DELETE button deletes the kid on the page and in mongoDB
- [x] the update is reflected on the `kidslist`
      ​

## Tasks

- [x] create a new branch feature/update-delete-kid
- [x] create a `EditKid` component and implement editing and deleting functions
- [x] implement the button and the save function to store the updated information
- [x] add a button and a cancel function to allow the user to cancel without saving the changes
- [x] update the `kidslist`after saving to reflect the changes

**Comment by milodevhh** [comment]
Hey Ulrike, sounds good to me.
