### ISSUE TITLE
US#7 - Add a child

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#17]
## Value Proposition

**As a** user
**I want to** add details of a child to the app
**so that** I can store events for this child. 
​

## Description

![Image](https://github.com/uwoch/capstone-project/assets/127953786/266e1434-5722-460f-ac58-a14d0476b7ae)

## Acceptance Criteria

- [x] A headline shows „Kind hinzufügen“
- [x] An input form is displayed in which the name and the date of birth can be entered
- [x] A date picker is used to pick the date
- [x] A button „Kind hinzufügen“ is displayed and clickable
- [x] Clicking the button adds the entered information in mongoDB and renders it to the `kidslist`

## Tasks

- [x] Create a new branch `feature/addchild`
- [x] Create a headline for the page
- [x] Create the input form for the name and date of birth
- [x] Create the button 
- [x] Write a function to store the entered information in mongoDB and on the homepage
