### ISSUE TITLE
US#2 - Details page child

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#2]
## Value Proposition

**As a** user
**I want to** click on a button next to one child 
**so that** I can see all stored information.

## Description

![US2-1](https://github.com/uwoch/capstone-project/assets/127953786/48785ef5-eb3f-4fab-8f03-469d461504f1)

![Image](https://github.com/uwoch/capstone-project/assets/127953786/b4160de7-9aa3-463b-8faf-653866545366)

## Acceptance Criteria

- [x] a button with an arrow is displayed and clickable next to each child
- [x] clicking on the button redirects to the details page of this child
- [x] all information about one child are shown on this page 

## Tasks

- [x] create a new branch feature/US-2
- [x] create the details pages for each child with dynamic routing
- [x] create the buttons
- [x] link the buttons to the corresponding details page
- [x] create a `KidProfile` component to show all stored information and the picture on the  details page

**Comment by CJAkkuec** [comment]
>  create a new branch

Does it have a name? 👁 👄  👁 

> create the buttons and link to the corresponding details page

You should probably mention that this will include dynamic routing. 🤔 

> write a function to show all stored information and the picture on the details page

Very strictly speaking you're not wrong, because a component is a function, but I'd suggest that you mention the components that you want to write, such as  potentially a `Milestone` component that renders the title, date and category.

The wireframe also implies that there's already going to be an edit feature, which is a different user story entirely imho. :)

**Comment by uwoch** [comment]
Thanks for your comments. You are right, I changed the US and will I will put all the editing of events in another US.

**Comment by alexander-bick** [comment]
It seems you perfectly integrated the aspects of yesterday´s review. It all makes sense to me 👌🏼🙂
