### ISSUE TITLE
U8# - Add Profile Image

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#21]
## Value Proposition

**As a** user
**I want to** add an image of my child
**so that** I can easily distinguish the profiles.
​

## Description

![Image](https://github.com/uwoch/capstone-project/assets/127953786/3dbbb02d-8c71-43ca-ab13-f91064472b4c)

## Acceptance Criteria

- [x] an image upload button is shown on the `KidForm`
- [x] using the upload button for a picture stores the image in cloudinary and the link in mongoDB
- [x] the picture is shown as a profile picture on the homepage and on the details page of each child
      ​

## Tasks

- [x] create a branch `feature/addimage`
- [x] create the image upload button
- [x] implement the function to store the image for the correct child in mongoDB

**Comment by milodevhh** [comment]
Hey Ulrike, sounds good to me, Do you already use cloudinary somewhere else in your app?

**Comment by uwoch** [comment]
Thanks! No, not yet. I tried to use it to store pictures to the events, but I couldn´t make it work. I hope I can make it this time...
