### ISSUE TITLE
US#10 - Final Styling

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#24]
## Value Proposition

**As a** user
**I want to** have a well structured and pretty app
**so that** I find my way around and enjoy using it.
​

## Description

I don´t have a scribble for the final look.
​

## Acceptance Criteria

- [x] the app has a overall final appearance
- [x] all elements of the app are looking like they should
      ​

## Tasks

- [x] create a new branch feature/styling
- [x] make layout changes
