### ISSUE TITLE
US#3 - "Add event" form

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#3]
## Value Proposition

**As a** user
**I want to** store an event for a child
**so that** I won´t forget what happend.
​
## Description

![Image](https://github.com/uwoch/capstone-project/assets/127953786/6d00e854-f7b6-4c00-8b04-6fef9c133163)

## Acceptance Criteria

- [x] an input form is displayed in which the event and the date can be entered
- [x] a placeholder shows possible events
- [x] a date picker is used to pick the date
(- [ ] a image upload is used to store images in Cloudinary and the image URL in mongoDB  - I couldn´t make it work, I will come back to this later)
- [x] a button „Log hinzufügen“ is displayed and clickable
- [x] clicking the button submits the data to MongoDB and the entered information is shown above the form

## Tasks

- [x] create a new branch `feature/event-form`
- [x] create a form with two input fields, one for the event title and one for the date
- [x] install React `DatePicker` for the date
(- [ ] create an image upload and use cloudinary to store the images  - I couldn´t make it work, I will come back to this later)
- [x] create the button to store the event
- [x] write a function to show all entered information on the page

**Comment by CJAkkuec** [comment]
>  clicking the button redirects the user to the details page of this child and shows the entered information

I'm assuming it also submits the data 👀 ?

> create a new branch US-3

I'd hugely prefer feature branches were named a little more verbosely, such as `event-form`.

> create an input form for the event title and date

Maybe something like "create a form with two input fields for the title and date of the event". 🤔

**Comment by uwoch** [comment]
Thanks! I changed that.

**Comment by FelineHuhn** [comment]
You did a good job incorporating the suggestions, looks good now. 🚀
