### ISSUE TITLE
US#4 - List of all children

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#4]
## Value Proposition

**As a** user  
**I want to** see a list of all children on the homepage
**so that** I can choose for which child I want to add an event.
​

## Description

![US4](https://github.com/uwoch/capstone-project/assets/127953786/20ce4b09-3d63-4501-ad3c-4578446a84a6)

## Acceptance Criteria

- [ ] A headline shows „Willkommen bei Kids-Log“
- [ ] A sub-headline shows „Alle Meilen deines Kindes in einer App!“
- [ ] A paragraph shows „Für welches Kind möchtest du loggen?“
- [ ] A list of all entered children is shown
      ​

## Tasks

- [ ] Create a new branch
- [ ] Create a headline for the page
- [ ] Create a sub-headline for the page
- [ ] Create a function to show all new entries in a list on this page (and no longer on the "Create a child's profile" page)
