### ISSUE TITLE
US#5 - Header and Nav

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#5]
## Value Proposition

**As a** user 
**I want to** be able to see on which site I am and switch between them
**so that** I can use the app completely.
​

## Description

![US5](https://github.com/uwoch/capstone-project/assets/127953786/602c1572-6c32-48c6-9806-24062243181c)
​

## Acceptance Criteria

- [ ] Describe every scenario in detail
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, testing
- [ ] ...
      ​

## Complexity

M (T-Shirt Sizes XS to XL)
