### ISSUE TITLE
US#5 - Header and nav

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#6]
## Value Proposition

**As a** user 
**I want to** be able to go back to the homepage from every site
**so that** I can choose another kid to store events for.
​

## Description

![Image](https://github.com/uwoch/capstone-project/assets/127953786/c8b12b88-ab23-494f-872a-94b9b1ed3fc1)

## Acceptance Criteria

- [x] a header shows the logo and the headline
- [x] the footer shows a home icon 
- [x] clicking the icon directs to the right page

## Tasks

- [x] create a new branch feature/nav
- [x] create a header
- [x] create a logo
- [x] embed the logo and the headline to the header
- [x] create a footer
- [x] insert an icon as a link to the correct site

**Comment by DorisW3** [comment]
Hi Ulrike,

I like the cute animals you chose as profile pictures!! 🐰🐹🦝
And the styling of the header is also very nice.
