### ISSUE TITLE
US#5 - Styling the App

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#7]
## Value Proposition

**As a** ... (User, Author, logged in User...)  
**I want to** ... (describe the goal)  
**so that** ... (describe the reason)  
​

## Description

... (Wireframe, scribble, design)
​

## Acceptance Criteria

- [ ] Describe every scenario in detail
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, testing
- [ ] ...
      ​

## Complexity

M (T-Shirt Sizes XS to XL)
