### ISSUE TITLE
US#4 - Edit  and delete events

### ISSUE THREAD

**Issue by uwoch** [uwoch/capstone-project#9]
## Value Proposition

**As a** user
**I want to** edit and delete information
**so that** my app is always up to date.
​

## Description

![Image](https://github.com/uwoch/capstone-project/assets/127953786/5ece2262-554f-4c35-bf95-1290352a1fec)

## Acceptance Criteria

- [x] a button "Bearbeiten" and button "Ereignis löschen" are shown under each event
- [x] clicking the button "Bearbeiten" leads to an edit form on which the user can edit the event
- [x] a button "Speichern" is shown with which the user can save the changes
- [x] a button "Abbrechen" is shown so the user has the option to cancel without saving the changes
- [x] clicking the button "Ereignis löschen" deletes the event on the page and in mongoDB
- [x] the update is reflected on the details page
      ​

## Tasks

- [x] create a new branch `feature/update-delete`
- [x] create a `Event`component and implement editing and deleting functions 
- [x] implement the button and the save function to store the updated information
- [x] add a button and a cancel function to allow the user to cancel without saving the changes
- [x] update the details page after saving to reflect the changes

**Comment by AlexDernov** [comment]
LGTM!👍🏻
